### ISSUE TITLE
Support For Providing Namespace at Run Time

### ISSUE THREAD

**Issue by Agrawalmahin** [aerospike/java-object-mapper#103]
Can we have support for providing the namespace at runtime, instead of hardcoding it on our beans, [I also don't want to provide it in env variables or system properties], I have some multitenancy use cases, where on run time, I will be deciding based on some parameters, which namespace to use .

Maybe an interface called NamespaceResolver, which has the default impl as the current one, and we can easily override the interface and provide the name space accordingly.?
So we will also need the ability to set it, maybe we can do that in while creating AeroMapper ?
Ans set it in ClassCacheEntry as well.
and change the getNamespace methods implementation to use NamespaceResover?

**Comment by reugn** [comment]
Hi @Agrawalmahin, we see interest in being able to provide a dynamic namespace for beans. We will look into supporting this in future releases.

**Comment by Agrawalmahin** [comment]
Hey any updates on this?
by when this would be supported or is this in progress?

**Comment by reugn** [comment]
@Agrawalmahin, no estimations at the moment.

**Comment by tim-aero** [comment]
This has been implemented using [external configuration](https://github.com/aerospike/java-object-mapper?tab=readme-ov-file#external-configuration-file). Any namespace specified in the external configuration or the code version of the external configuration file (`AeroMapper.Builder.withClassConfigurations` for example) will override any annotation provided, including the namespace.
