### ISSUE TITLE
NullPointerException in ClassCacheEntry 

### ISSUE THREAD

**Issue by Agrawalmahin** [aerospike/java-object-mapper#104]
When doing batchReads, on primary key on a high load, I am seeing NullPointers, attaching stack trace for the same
lib version 2.0.1

`Object[] args = new Object[constructorParamBins.length];`

```
ClassCacheEntry.java in constructAndHydrateFromJavaMap at line 1038
ClassCacheEntry.java in constructAndHydrate at line 946
ClassCacheEntry.java in constructAndHydrate at line 918
MappingConverter.java in convertToObject at line 110
AeroMapper.java in readBatch at line 378
AeroMapper.java in read at line 325
AeroMapper.java in read at line 304
AeroMapper.java in read at line 299
```

**Comment by roimenashe** [comment]
@Agrawalmahin 
Please upgrade Java Object Mapper to the latest version 2.0.3, it contains many changes around the ClassCacheEntry that could potentially address this issue.
There are no breaking changes between 2.0.1 and 2.0.3 so the upgrade should be easy.
If the problem still occurs we will be happy to assist.
Thank you.

**Comment by Agrawalmahin** [comment]
Sure, Let me give it a try, I will update this thread.
Thank you!

**Comment by Agrawalmahin** [comment]
@roimenashe 
we ran some tests, similar to the previous ones, we were not able to reproduce the same errors again.
Closing this issue for now, will reopen, if we see the errors again.
Thank you!!
