### ISSUE TITLE
Unable to update specific bins on embeeded object

### ISSUE THREAD

**Issue by x80486** [aerospike/java-object-mapper#111]
I have a simple class hierarchy:

```java
@AerospikeRecord(namespace = "ns", set = "st")
public class A {
  @AerospikeEmbed
  @AerospikeBin(name = "b")
  private B b;

  @AerospikeEmbed
  @AerospikeBin(name = "c")
  private C c;
}

@AerospikeRecord
public class B { // B and C are similar
  @AerospikeBin(name = "ba")
  private String ba;

  @AerospikeBin(name = "bb")
  private String bb;
}
```

I'm trying to specify certain fields that should be updated only:

```java
// A(b = B(ba = BA, bb = BB), c = C(ca = CA, cb = CB))
b.ba = "Something Else";
mapper.update(a, List.of("b")); // ...this updates the entire map, rather than only ba
```

Is there a way to accomplish what I'm looking for? According to my tests, if I pass the specific `bin` for the embedded object, the entire object is updated in Aerospike (that's expected somehow), but I'm currently unable to select the specific bins for such embedded objects:

```java
mapper.update(a, List.of("ba")); // Not working
mapper.update(a, List.of("cb")); // Not working
```

Am I doing something wrong here, or do I have to plug into the actual client and `MapOperation`s to accomplish that?

**Comment by roimenashe** [comment]
@x80486 
Not sure exactly if that solves your issue but if I run this code/test:
```java
package com.aerospike.mapper;

import com.aerospike.mapper.annotations.AerospikeBin;
import com.aerospike.mapper.annotations.AerospikeEmbed;
import com.aerospike.mapper.annotations.AerospikeKey;
import com.aerospike.mapper.annotations.AerospikeRecord;
import com.aerospike.mapper.tools.AeroMapper;
import org.junit.jupiter.api.Test;

public class test extends AeroMapperBaseTest {

    @AerospikeRecord(namespace = "test", set = "a")
    public static class A {

        @AerospikeKey
        private int id;

        @AerospikeEmbed
        @AerospikeBin(name = "b")
        private B b;

        @AerospikeEmbed
        @AerospikeBin(name = "c")
        private C c;

        public A(int id, B b, C c) {
            super();
            this.b = b;
            this.c = c;
        }

        public A() {

        }
    }

    @AerospikeRecord(namespace = "test", set = "b")
    public static class B {
        @AerospikeKey
        private int id;

        @AerospikeBin(name = "ba")
        private String ba;

        @AerospikeBin(name = "bb")
        private String bb;

        public B(int id, String ba, String bb) {
            super();
            this.id = id;
            this.ba = ba;
            this.bb = bb;
        }

        public B() {

        }
    }

    @AerospikeRecord(namespace = "test", set = "c")
    public static class C {
        @AerospikeKey
        private int id;

        @AerospikeBin(name = "ba")
        private String ca;

        @AerospikeBin(name = "bb")
        private String cb;

        public C(int id, String ca, String cb) {
            super();
            this.id = id;
            this.ca = ca;
            this.cb = cb;
        }

        public C() {

        }
    }

    @Test
    public void test() {
        AeroMapper mapper = new AeroMapper.Builder(client).build();

        A a = new A(1, new B(2, "BA", "BB"), new C(3, "CA", "CB"));

        mapper.save(a);

        a.b.ba = "Something Else";
        mapper.update(a, "b"); // ...this updates the entire map, rather than only ba
    }
}
```

Then I get this before the update:
![Screen Shot 2022-03-09 at 23 05 39](https://user-images.githubusercontent.com/33356310/157536082-9be476de-7076-4c29-8b6b-c2905623ede6.png)

And after the update:
![Screen Shot 2022-03-09 at 23 06 43](https://user-images.githubusercontent.com/33356310/157536163-8b4dd8ce-e355-4167-9ccc-3e625ca5d19e.png)

So the only change is the inner "ba" of bin "b", which is the expected results?
If I am missing something here please add more details such as how you instantiate your objects, what are the expected results and what you are currently getting.

**Comment by x80486** [comment]
@roimenashe, thanks for looking into this one :raised_hands:

My test case is very similar, but I was trying to "simulate" two processes (far from ideal the test implementation) writing to each field indistinctly:

```java
@Test
public void test() {
  final AeroMapper mapper = new AeroMapper.Builder(client).build();
  A a = new A(1, new B(2, "BA", "BB"), new C(3, "CA", "CB"));
  mapper.save(a);
  final A p1 = mapper.read(A.class, 1);
  final A p2 = mapper.read(A.class, 1);
  p1.b.ba = "One the These";
  p2.b.bb = "Won't Succeed";
  mapper.update(p1, "b");
  mapper.update(p2, "b");
}
```

**Comment by roimenashe** [comment]
@x80486 
An update() operation can update a specific bin when updating a record (thats the lowest resolution) but in your case you are reading the same object twice and then update the same bin with by specific the two different changed objects so it is not atomic operation (the last one wins), if you updated 2 different bins then it would work - in this case your best option is to update the nested bb/ba field in "b" bin directly using a single Aerospike Java Client call (operate probably).

Regarding your second question - check out "Key" section of the README page: https://github.com/aerospike/java-object-mapper#keys.

**Comment by x80486** [comment]
Right, that's what currently happens. Initially I was asking if there was a way to write that update (without using the low level `Aerospike` client directly) in a way that one instance executes `mapper.update(a, List.of("b.ba"))`, while the other one executes `mapper.update(a, List.of("b.bb"))`.

So far with that notation: `"b.ba"` or just `"ba"`, the operation fails, so I'm not sure what's the right syntax to "navigate down" the embedded objects to select the bins within them.

**Comment by roimenashe** [comment]
@x80486 
In your case I don't think there is a way to achieve that using the Java Object Mapper.
I would suggest using the Aerospike Java Client operate() with MapOperation, you can check out some examples here: https://github.com/aerospike/aerospike-client-java/blob/master/test/src/com/aerospike/test/sync/basic/TestOperateMap.java

It will allow you to perform your update operation in a single database call so 2 operations can't conflict and override each other.

**Comment by x80486** [comment]
Thanks for your help, @roimenashe. I'll use the Aerospike (Java) client instead for these cases, as suggested.
