### ISSUE TITLE
Embedded objects stored as Aerospike Maps don't hit the bin length limitations

### ISSUE THREAD

**Issue by x80486** [aerospike/java-object-mapper#112]
Suppose I have a simple class hierarchy:

```java
@AerospikeRecord(namespace = "ns", set = "st")
public class A {
  @AerospikeEmbed(type = EmbedType.MAP)
  @AerospikeBin(name = "b")
  private B b;

  @AerospikeEmbed(type = EmbedType.MAP)
  @AerospikeBin(name = "c")
  private C c;
}

@AerospikeRecord
public class B { // B and C are similar
  @AerospikeBin(name = "super_long_bin_name_that_exceeds_character_length_limits")
  private String ba;

  @AerospikeBin(name = "bb")
  private String bb;
}
```

Aerospike has a limitation on bin names — they should be within `14` characters or less.

Somehow, I think the internal fields/members from those embedded objects are not really stored in bins, even though they are annotated with `@AerospikeBin`.

Since I'm not hitting the limit error with those, would you folks be able to clarify that? I can certainly go through the StackOverflow route first if required.

**Comment by roimenashe** [comment]
@x80486 If you only store B as an embedded field in A and not store it directly in Aerospike then yes you won't hit the 14 char limitation error (which is an Aerospike Java Client error).
I still think its best to follow the max 14 chars even if you are not storing B directly, you might do so in the future.

**Comment by x80486** [comment]
The only problem to follow such convention for me is that some time, the bin names get a little bit cryptic because it doesn't really resembles the field/member they are annotating.

But again, in this case it wouldn't be the case. In general, I would follow that, but this time I'm not going to be able to treat that object (e.g.: `B` embedded in `A`) as a single record, so it's going to be like a `Map` all the time.

Thanks for the clarifications :tropical_drink:
