### ISSUE TITLE
Support setting/specifying the record's set dynamically

### ISSUE THREAD

**Issue by x80486** [aerospike/java-object-mapper#113]
The current `@AerospikeRecord` annotation makes it very convenient to define the namespace and set to be used.

Sometimes, users would like to change these dynamically to slice the data in more convenient ways. For instance, the same data (with the same structure) is distributed in different (Aerospike) sets because the amount, security constraints, etc.

Would it be possible to be able to provide different identifiers/names for a given model (read: Aerospike record)?

**Comment by tfaulkes** [comment]
Can you give more details on what you’re trying to achieve? Normally a model (Java POJO) is mapped to a particular namespace/set combination, and the class of the POJO defines what the structure of those records looks like. If you have instances of the same class arbitrarily defining which namespace / set to map to, you would have to be careful to ensure that you’re reading records with the right structure when reading them back.

One way to achieve this at the moment is override the namespace / set in a YAML configuration when you’re building the object mapper. This would fix it for all objects of that class type for this session. Is this flexible enough for your needs?

On Apr 1, 2022, at 1:55 PM, x80486 ***@***.***> wrote:

﻿

The current @AerospikeRecord annotation makes it very convenient to define the namespace and set to be used.

Sometimes, users would like to change these dynamically to slice the data in more convenient ways.

Would it be possible to be able to provide different identifiers/names for a given model (read: Aerospike record)?

**Comment by x80486** [comment]
I'm trying to use the same model between different sets to avoid scalability issues.

Say the model in use is: `Foo {id, availability, price, status}`. In my case, the goal is, while having several `Elasticsearch` indexes — for instance: `us`, `uk`, `ch`, etc., to be able to perform _partial updates_ on the indices. We use `Aerospike` as the interim "data store" to avoid reading from `Elasticsearch` all the time to compute the diff from the incoming data and the actual data that's in `Elasticsearch` — among some other reasons as well.

As you can see, the model is the same, but I would like to mimic the same structure I have for `Elasticsearch` in `Aerospike`, hence the need to change the sets at runtime.

**Comment by roimenashe** [comment]
@x80486 
For some cases a Namespace/Set Placeholder can be useful: https://github.com/aerospike/java-object-mapper#Placeholder-replacement. It allow you to change the Namespace/Set reference of an `@AerospikeRecord` object dynamically, be aware that it is not a thread safe operation - if you change the value of system param/env variable it will direct all writes to the current value.

There is a feature request for providing a "real" dynamic namespace/set at runtime: https://github.com/aerospike/java-object-mapper/issues/103, it is currently under consideration.

**Comment by x80486** [comment]
OK, great. I'm using that as well, but I didn't take my chances changing that value at runtime if it's not well supported. I subscribed to the other issue.

Thanks for the info!
