### ISSUE TITLE
Dynamically set TTL on an individual record

### ISSUE THREAD

**Issue by ajeetdsouza** [aerospike/java-object-mapper#132]
Hi, I'm trying to set a TTL when saving an individual record, but the `AeroMapper.save()` function overrides it. How can I save a record with a different TTL than the default?

This is what I'm trying to do:

```java
WritePolicy policy = new WritePolicy(client.writePolicyDefault);
policy.expiration = 10;
mapper.save(policy, shortLink);
```

This is the offending code: https://github.com/aerospike/java-object-mapper/blob/a0d1164944413cbb225878456d0fedc783d9126d/src/main/java/com/aerospike/mapper/tools/AeroMapper.java#L229-L231

**Comment by realmgic** [comment]
Got it, @ajeetdsouza - sorry I couldn't be more helpful
