### ISSUE TITLE
Infinite recursion with translateError method

### ISSUE THREAD

**Issue by Hartigan** [aerospike/java-object-mapper#153]
Hello

I face infinite recursion problem with method `translateError` https://github.com/aerospike/java-object-mapper/blob/a62ab124435d712ee8da07cbf84a08c1a0d03a19/src/main/java/com/aerospike/mapper/tools/ReactiveAeroMapper.java#L420

I think method should take inner error if exception is `AerospikeException`.

**Comment by roimenashe** [comment]
Hi @Hartigan, thanks!
This translation is redundant and causes an infinite loop, removed in: https://github.com/aerospike/java-object-mapper/pull/155.
This fix will be included in the next version of Java Object Mapper: `2.3.3`
