### ISSUE TITLE
Return List of entities from query

### ISSUE THREAD

**Issue by sujeet100** [aerospike/java-object-mapper#75]
AeroMapper allows you to create queries with filters and expressions but returns void. So if you want to return the RecordSet into a list you need to do the processing yourselves using the processor lambda. The code looks like this

```
List<User> users = new ArrayList<>();
        aeroMapper.query(policy, User.class, x -> {
            users.add(x);
            return true;
        }, Filter.equal("age", 33));
        return users;
```
Is it possible to add overriden query methods in the Aeromapper which returns List of entities? So that the same code would look like this

`return aeroMapper.query(policy, User.class, Filter.equal("age", 33));`

Happy to submit a PR for this.

**Comment by tfaulkes** [comment]
Thank you for this, it's a good idea. The obvious thing to watch out for is accidentally running out of memory if you process a result set bigger than you expected, but I think that's an acceptable risk and I like the convenience of the overload you suggest. It's probably worthwhile having a similar overload on the scan too for small datasets.

If you're happy to submit a PR for this it would be great. If you would prefer not, please let me know and I will happily add it.

Thanks for the suggestion to improve the Object Mapper, keep them coming!

**Comment by sujeet100** [comment]
Added initial implementation. Please review and let me know if there are any review comments :)
