### ISSUE TITLE
Unable to do Expression search with read by Primary key

### ISSUE THREAD

**Issue by atul31313** [aerospike/java-object-mapper#80]
We have a use case in which we need to add filter expressions in Policy on read by Primary Key to filter on some other bins as well. Since subsequent reads from object mapper will be reading from the cache using `LoadedObjectResolver.get(key)` we are not able to apply expressions on subsequent read calls for a read by a Primary key.

So the tentative solution for this could be to add a if check when we call `LoadedObjectResolver.get(key)` to check if there are filters in the readPolicy. If there are any filterExpressions then it should not be fetching the record from the cache but instead it should be from the Aerospike database.

**Comment by roimenashe** [comment]
@atul31313 Thanks for noticing!
https://github.com/aerospike/java-object-mapper/pull/81 by @reugn should fix it.
Changes will be included in the next version of Java Object Mapper 1.4.1.
We already released 1.4.1 to maven central - it will take up to 24 hours to sync.

Please keep us updated.

**Comment by atul31313** [comment]
That's really great @roimenashe Thanks for the quick fix it really helps.

**Comment by roimenashe** [comment]
@atul31313 No problem, thanks @reugn for the actual fix.
Closing.
