### ISSUE TITLE
One set limitation

### ISSUE THREAD

**Issue by evolvednight** [aerospike/java-object-mapper#86]
According to the documentation.  
I have two question
1. each java object should be map to its own aerospike set.  What happens if you only have one set?  Is there a way to store everything in the same set? Given there is 20 different objects?
2. There was a need for  @AerospikeKey.   In my case there was 1 complex object without any id with 4 list/set of objects.  Those 4 list/set of objects does have IDs.  I am guessing the best way I should approach this is create the complex object and get those 4 different object with their respective IDs and map those 4 objects into the complex object?  but what happen if I only have one set within my aerospike?

**Comment by tfaulkes** [comment]
I have a couple of questions based on your issue. Aerospike gives 1023 sets per namespace, so why would you want to store different objects in the same set? The normal Aerospike deployment has say customers in a Customers set, accounts in an Account set, etc. Why are you looking at storing the different classes in the same set?

That being said, you can store different objects in the same set in the Object Mapper. For example:
```
public class JavaObjectMapper {
	@AerospikeRecord(namespace = "test", set="common")
	public static class Customer {
		@AerospikeKey
		public int id;
		public String name;
		public Date dob;
		@Override
		public String toString() {
			return String.format("{id=%d,name='%s',dob=%s}", id, name, dob);
		}
	}
	
	@AerospikeRecord(namespace = "test", set="common")
	public static class Doc {
		@AerospikeKey
		public int id;
		private String data;
		
		@Override
		public String toString() {
			return String.format("{id=%d,data='%s'}", id, data);
		}
	}
		

	public static void main(String[] args) {
		IAerospikeClient client = new AerospikeClient("127.0.0.1", 3000);
		AeroMapper mapper = new AeroMapper.Builder(client).build();
		Customer customer = new Customer();
		customer.id  = 1;
		customer.name = "bob";
		customer.dob = new Date();
		
		Doc doc = new Doc();
		doc.id = 3;
		doc.data = "This is some data";
		
		mapper.save(customer, doc);
		Customer cust = mapper.read(Customer.class, customer.id);
		Doc doc2 = mapper.read(Doc.class, doc.id);
		System.out.println(cust);
		System.out.println(doc2);
		
		client.close();
	}
}
```
There are no markers in the stored records which indicate the type of the record being stored:
```
aql> select * from test.common
+---------------------+----+---------------+-------+
| data                | id | dob           | name  |
+---------------------+----+---------------+-------+
| "This is some data" | 3  |               |       |
|                     | 1  | 1637711578629 | "bob" |
+---------------------+----+---------------+-------+
2 rows in set (0.189 secs)
```
So if you do a scan across the set the object mapper will not know which classes to which to map the items. Is this an issue in your use case?

One way around this is to have all your objects inherit from a common superclass and perform the object mapping at the superclass level. The child classes will inherit the namespace and set from the superclass and the object mapper will know to put the type information in the references. See [Subclasses](https://github.com/aerospike/java-object-mapper#subclasses)

As for your second question, I'm curious why you do not have an AerospikeKey. You're trying to save the complex object in the database, you need to identify a key which you will use to save the object and subsequently load the object again. If you don't give it a key, how will you load it? Can you give more details about your use case please?

**Comment by tfaulkes** [comment]
Ah, makes sense. So you want everything in 1 table, but you want them to have overlapping ids. So in my example, you might have a Customer with ID 1 and a Doc with ID 1. But you want them in the same table and you don't want to change the keys.

You can achieve this with some annotations on the object mapper. It's a little convoluted, but works nicely. Here's an example:

```
	@AerospikeRecord(namespace = "test", set="common")
	public static class Customer {
		@AerospikeExclude
		public static final String PREFIX = "CUST:";
		@AerospikeExclude
		private int id;
		private String name;
		private Date dob;
		
		@AerospikeKey
		@AerospikeGetter(name = "key")
		public String getKey() {
			return PREFIX + this.id;
		}
		@AerospikeKey(setter = true)
		@AerospikeSetter(name = "key")
		public void setKey(String key) {
			this.id = Integer.parseInt(key.substring(PREFIX.length()));
		}
		@Override
		public String toString() {
			return String.format("{id=%d,name='%s',dob=%s}", id, name, dob);
		}
	}
	
	@AerospikeRecord(namespace = "test", set="common")
	public static class Doc {
		@AerospikeExclude
		public static final String PREFIX = "DOC:";
		@AerospikeExclude
		public int id;
		private String data;
		
		@AerospikeKey
		@AerospikeGetter(name = "key")
		public String getKey() {
			return PREFIX + this.id;
		}
		@AerospikeKey(setter = true)
		@AerospikeSetter(name = "key")
		public void setKey(String key) {
			this.id = Integer.parseInt(key.substring(PREFIX.length()));
		}

		@Override
		public String toString() {
			return String.format("{id=%d,data='%s'}", id, data);
		}
	}
	
	@AerospikeRecord(namespace="test", set="ref")
	public static class ReferencingClass {
		@AerospikeKey
		public int id;
		public Customer cust;
		public Doc doc;
	}
		

	public static void main(String[] args) {
		IAerospikeClient client = new AerospikeClient("127.0.0.1", 3000);
		AeroMapper mapper = new AeroMapper.Builder(client).build();
		Customer customer = new Customer();
		customer.id  = 1;
		customer.name = "tim";
		customer.dob = new Date();
		
		Doc doc = new Doc();
		doc.id = 1;
		doc.data = "This is some data";
		
		mapper.save(customer, doc);
		Customer cust = mapper.read(Customer.class, customer.getKey());
		Doc doc2 = mapper.read(Doc.class, doc.getKey());
		System.out.println(cust);
		System.out.println(doc2);
		
		ReferencingClass ref = new ReferencingClass();
		ref.id = 2;
		ref.cust = cust;
		ref.doc = doc;
		mapper.save(null, ref);
		client.close();
	}
```

With the classes like this, the data in the database looks like:

```
aql> select * from test.common
+---------------+----------+-------+---------------------+
| dob           | key      | name  | data                |
+---------------+----------+-------+---------------------+
| 1638211153127 | "CUST:1" | "tim" |                     |
|               | "DOC:1"  |       | "This is some data" |
+---------------+----------+-------+---------------------+
```

Note that the prefix has been added to the key and the id column is no longer there. To get this to work we have to make some changes:

- The id field no longer needs to get stored in the database, so it's marked as AerospikeExclude
- There are getters and setters for the key, and they have been annotated with AerospikeKey and AerospikeGetter/Setter. (If they were just annotated with AerospikeKey they would be used to store the record but would NOT be stored in the database).
- The PREFIX field has also been excluded. There's no smarts to ignore static + final fields, but I might change this behaviour. 

Note that I've done this on 2 classes for illustrative purposes. In reality I would make these classes subclasses of a common parent and use inheritance to minimise the amount of boilerplate code.

**Comment by evolvednight** [comment]
Tim it seems to work with a small object.  I am testing with a larger complex object.  Let me get back to this issue tomorrow.  That AerospikeExclude annotation is super handy.

**Comment by roimenashe** [comment]
@tfaulkes Thanks for the detailed solution Tim!
@evolvednight Can I close this issue?

**Comment by evolvednight** [comment]
The answer was great!  I was able to get it to work on a large object too.  with many @aerospikebins and @aerospikeembed annotation.
One more question.  Not sure should I ask here or ask in a new issue.
Is there a way to not right so many aerospikebins or aerospikeembed annotation?

**Comment by roimenashe** [comment]
@evolvednight
Thanks good to hear,
Depends on what your trying to accomplish, 
For @AerospikeBin annotation - you can use @AerospikeRecord which by default maps all class fields as bins (https://github.com/aerospike/java-object-mapper/blob/49e58107e11defd772c777f7db6450b835910639/src/main/java/com/aerospike/mapper/annotations/AerospikeRecord.java#L22 and then use @AerospikeExclude to exclude specific bins and @AerospikeBin(name= "blabla") to change the name of specific bins.
You can see a good example for that in:
https://github.com/aerospike/java-object-mapper/blob/main/src/test/java/com/aerospike/mapper/model/Account.java

As for the @AerospikeEmbed annotation, if you want to embed a specific type into Aerospike bin then you need to explicitly use this annotation, there is no way of reducing this annotation if the purpose is to embed the field.

**Comment by evolvednight** [comment]
Yeah one issue with this is that there are many fields with name over 14 characters. so I end up have to use many aerospikeBin annotation for each object

**Comment by roimenashe** [comment]
@evolvednight If most of your field names are over 14 characters, then yes you can't escape having multiple `@AerospikeBin` annotation in your class but its reasonable.

Can I consider this issue closed?

**Comment by evolvednight** [comment]
yes @roimenashe thank you so much and @tfaulkes as well
