### ISSUE TITLE
Aersopike Exception - Stored name of "ARecord" is used for both com.ARecord and com.ARecord 

### ISSUE THREAD

**Issue by agugan** [aerospike/java-object-mapper#90]
Hi Team,

When we are loading ~15 million records (of type ARecord) via kafka into aerospike, we are facing the following error for few records. 

com.aerospike.client.AerospikeException: Error -1: Stored name of "ARecord" is used for both com.ARecord and com.ARecord at com.aerospike.mapper.tools.ClassCache.setStoredName(ClassCache.java:90) at com.aerospike.mapper.tools.ClassCacheEntry.construct(ClassCacheEntry.java:160) at com.aerospike.mapper.tools.ClassCache.loadClass(ClassCache.java:75) at com.aerospike.mapper.tools.utils.MapperUtils.getEntryAndValidateNamespace(MapperUtils.java:11) at com.aerospike.mapper.tools.AeroMapper.save(AeroMapper.java:213) at com.aerospike.mapper.tools.AeroMapper.save(AeroMapper.java:202) at com.ARepository.save(A.java:18) at com.processor.ARecordProcessor.insert(ARecordProcessor.java:40) at com.processor.$ARecordProcessor$Definition$Intercepted.$$access$$insert(Unknown Source) at com.processor.$ARecordProcessor$Definition$Exec.dispatch(Unknown Source) at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128) at io.micronaut.tracing.interceptor.TraceInterceptor.intercept(TraceInterceptor.java:182) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) at com.processor.$ARecordProcessor$Definition$Intercepted.insert(Unknown Source) at com.listener.AListener.receive(AListener.java:57) at com.listener.$AListener$Definition$Intercepted.$$access$$receive(Unknown Source) at com.listener.$AListener$Definition$Exec.dispatch(Unknown Source) at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128) at com.listener.aspect.ConsumerListenerInterceptor.intercept(ConsumerListenerInterceptor.java:58) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) at io.micronaut.configuration.metrics.micrometer.intercept.TimedInterceptor.intercept(TimedInterceptor.java:128) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) at io.micronaut.aop.internal.intercepted.SynchronousInterceptedMethod.interceptResult(SynchronousInterceptedMethod.java:55) at io.micronaut.retry.intercept.DefaultRetryInterceptor.retrySync(DefaultRetryInterceptor.java:213) at io.micronaut.retry.intercept.DefaultRetryInterceptor.intercept(DefaultRetryInterceptor.java:120) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:92) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) at io.micronaut.tracing.interceptor.TraceInterceptor.intercept(TraceInterceptor.java:182) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) at com.listener.$AListener$Definition$Intercepted.receive(Unknown Source) at com.listener.$AListener$Definition$Exec.dispatch(Unknown Source) at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351) at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:76) at io.micronaut.core.bind.DefaultExecutableBinder$1.invoke(DefaultExecutableBinder.java:109) at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.processConsumerRecords(KafkaConsumerProcessor.java:482) at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.createConsumerThreadPollLoop(KafkaConsumerProcessor.java:426) at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$submitConsumerThread$6(KafkaConsumerProcessor.java:375) at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79) at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160) at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source).

 This is how our ARecord looks like
 ARecord.java 
 @AerospikeRecord(set="A", namespace="test", mapAll=false)
 public final class ARecord {
 
@AerospikeKey
 private String id;
 
 @AerospikeBin("mobileNo")
 private String mobileNumber;
}

we tried to reproduce it locally by running it in parallel threads and running a small dataload tests, but no success.
We need your help on this.

**Comment by roimenashe** [comment]
@agugan 
Thanks for discovering this bug, we have just released a new version of the Java Object Mapper 2.0.2 (https://github.com/aerospike/java-object-mapper/releases/tag/2.0.2) that should address it (it might take up to 24 hours to sync in Maven Central).

Please keep us updated.

**Comment by agugan** [comment]
Thanks @roimenashe and team for the quick fix. We are upgrading to the newer version. We will keep you posted.

**Comment by agugan** [comment]
It works as a charm team. Good to close the issue. Also if possible, I am curious to know how did you folks reproduce it?

**Comment by roimenashe** [comment]
@agugan 
Thanks for the update, we are happy that it fixed your issue.
We have suspected that this was a classic race condition scenario that evaluated in different threads trying to load the class entry at conflicting points, The fix was syncing the load entry part to achieve thread safety.
