### ISSUE TITLE
ArrayIndexOutOfBoundsException from ClassCacheEntry.getBins() as Bins is fetched with size of 0

### ISSUE THREAD

**Issue by atul3991** [aerospike/java-object-mapper#98]
Hi Team,
When we are loading ~1 million records via kafka into aerospike, we are facing the following error for few records.
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.aerospike.mapper.tools.ClassCacheEntry.getBins(ClassCacheEntry.java:825)
	at com.aerospike.mapper.tools.AeroMapper.save(AeroMapper.java:237)
	at com.aerospike.mapper.tools.AeroMapper.save(AeroMapper.java:202)

On debugging found that the bins count from the cache is returning the size as 0. Which causes ArrayIndexOutOfBoundsException.

This is not happening very often so unable to reproduce it.

**Comment by roimenashe** [comment]
@atul3991 
Hi, Thanks for sharing this issue with us.
Please add your entity class including all the Aerospike Java Object Mapper annotations.

**Comment by atul3991** [comment]
@roimenashe 
Here is the sample entity class including the java object mapper annotations used:
```
import com.aerospike.mapper.annotations.AerospikeBin;
import com.aerospike.mapper.annotations.AerospikeKey;
import com.aerospike.mapper.annotations.AerospikeRecord;
import com.metadata.BookMeta;

@AerospikeRecord(set = BookMeta.SET, namespace = "#{AEROSPIKE_NAMESPACE:test}", mapAll = false)
public final class Book {

    @AerospikeKey
    @AerospikeBin(name = BookMeta.BinNames.PRIMARY_KEY)
    private String primaryKey;

    @AerospikeBin(name = BookMeta.BinNames.NAME)
    private String name;

    @AerospikeBin(name = BookMeta.BinNames.Author)
    private String author;
}
```
And the above error is thrown when we call BookRepository.save(bookRecord);

**Comment by roimenashe** [comment]
@atul3991 
Thanks! looking into your problem, one last thing what version of Java Object Mapper are you using? if it isn't the latest  - is it possible to upgrade?

**Comment by atul3991** [comment]
@roimenashe 
We are using the latest object mapper only: `com.aerospike:java-object-mapper:2.0.2`

**Comment by atul3991** [comment]
Hi @reugn,
Thanks for the quick PR with the code changes. Just wanted to check if the issue was fixed in 2.0.3 release? Can we upgrade our Aerospike object mapper version?

**Comment by reugn** [comment]
Hi @atul3991. Yes, v2.0.3 contains the fix. Please upgrade to the latest version and let us know if this resolves the issue.

**Comment by atul3991** [comment]
Sure @reugn we will upgrade the object mapper and test if this fixes the issue. Thanks for so quick fix

**Comment by atul3991** [comment]
Will update if we do not get this issue in this thread..

**Comment by atul3991** [comment]
I think we can close this issue as we did not see any more of this error. Thanks @reugn for your quick help
